mutation CreateNewProject($title: String!, $description: String, $dueDate: Date!, $startDate: Date!, $status: String!, $clientId: UUID!) @auth(level: USER) {
  project_insert(
    data: {
      title: $title,
      description: $description,
      dueDate: $dueDate,
      startDate: $startDate,
      status: $status,
      clientId: $clientId,
      projectManagerId_expr: "auth.uid",
      createdAt_expr: "request.time"
    }
  )
}

query GetMyProjects @auth(level: USER) {
  projects(where: { projectManagerId: { eq_expr: "auth.uid" } }) {
    id
    title
    status
    dueDate
    client {
      name
      company
    }
  }
}

query GetPublicClients @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  clients {
    id
    name
    company
    email
  }
}

mutation UpdateProjectStatus($projectId: UUID!, $newStatus: String!) @auth(expr: "auth.uid != nil && resource.project.projectManagerId == auth.uid", insecureReason: "Only the project manager can update the status of their project.") {
  project_update(
    key: { id: $projectId },
    data: { status: $newStatus }
  )
}